Upgrade OPA server and Vault server versions.
fybrik/fybrik pull request #1870
Opened 2023-01-05 07:46 UTC by revit13

Signed-off-by: Revital Sur <eres@il.ibm.com>

2023-01-09 20:26 UTC, roytman commented
try to use in go.mod:

> github.com/hashicorp/vault/api v1.8.2
> github.com/hashicorp/vault/sdk v0.6.2 // indirect
>

2023-01-10 20:41 UTC, roytman approved these changes

2023-01-10 20:42 UTC, roytman commented
@shlomitk1 can you take a look please, that I did not miss something?

2023-01-11 18:14 UTC, roytman requested changes
After merging #1855 , please rerun `make generate`

2023-01-12 07:11 UTC, shlomitk1 approved these changes

2023-01-13 18:30 UTC, roytman approved these changes

2023-01-13 20:15 UTC, merged