Promote supported K8s versions to 1.23 - 1.25
fybrik/fybrik pull request #1901
Opened 2023-01-15 12:24 UTC by roytman

Promote supported K8s versions to 1.23 - 1.25

/fixes https://github.com/fybrik/fybrik/issues/1900 

Signed-off-by: Alexey Roytman <roytman@il.ibm.com>

2023-01-15 15:23 UTC, shlomitk1 commented on site/docs/contribute/environment.md
> +On the other side, for fybrik v0.6.x, Helm v3.7 or above is required. Fybrik v1.2 requires Helm 1.10
3.10

2023-01-15 15:23 UTC, shlomitk1 requested changes
Helm 3.10 instead of 1.10

2023-01-15 16:27 UTC, roytman commented on site/docs/contribute/environment.md
> +On the other side, for fybrik v0.6.x, Helm v3.7 or above is required. Fybrik v1.2 requires Helm 1.10
fixed

2023-01-15 19:28 UTC, roytman commented
> Helm 3.10 instead of 1.10

done

2023-01-16 07:12 UTC, revit13 submitted a review, later dismissed

2023-01-18 09:50 UTC, shlomitk1 approved these changes

2023-01-18 11:06 UTC, merged