initial version
fybrik/fybrik pull request #962
Opened 2021-11-16 14:59 UTC by shlomitk1

Signed-off-by: Shlomit Koyfman <shlomitk@il.ibm.com>

Implementation of OPA-based evaluation of config policies according to #932

2021-11-23 13:22 UTC, simanadler requested changes
I didn't read through all of the code yet, but there are some important initial comments.

2021-11-23 15:35 UTC, shlomitk1 commented on pkg/adminconfig/rego_file_evaluator.go
> +const RegoPolicyDirectory = "/tmp/adminconfig/"
This directory inside the pod is set during the deployment, and the files are copied automatically from a configmap. Similar to what we do with taxonomy files or governance policies.

2021-11-23 15:47 UTC, shlomitk1 commented on manager/controllers/app/plotter_generator.go
> +		if len(item.Configuration.ConfigDecisions[app.Read].DeploymentRestrictions.Clusters) > 0 {
I understand what you are saying. That it does not matter whether the capability is called read, write or xyz as long as it has a required source, sink or api, and that's how we connect them. OK, I'll try to change.

2021-11-30 17:35 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/default_policies.rego
> +# allow implicit copies by default
Moved to the quick-start policies.

2021-11-30 18:44 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/quickstart_policies.rego
> +config[{"copy": decision}] {
OK.

2021-12-01 07:23 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/quickstart_policies.rego
> +    clusters := [ data.clusters[i].name | data.clusters[i].metadata.region == input.request.dataset.geography ]
@simanadler In this case, the evaluator does not require access to infrastructure, correct?

2021-12-05 19:33 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/quickstart_policies.rego
> +    decision := {"policy": policy, "deploy": true, "restrictions": {"clusters": clusters}}
Done

2021-12-05 20:16 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/quickstart_policies.rego
> +    clusters := [ data.clusters[i].name | data.clusters[i].metadata.region == input.request.dataset.geography ]
Done

2021-12-05 20:16 UTC, shlomitk1 commented on charts/fybrik/files/adminconfig/default_policies.rego
> +    policy := {"ID": "read-default", "description":"Read capability is requested for read workloads"}
I'll add in a separate PR.

2021-12-05 20:17 UTC, shlomitk1 commented on manager/controllers/app/plotter_generator.go
> +		if len(item.Configuration.ConfigDecisions[app.Copy].DeploymentRestrictions.Clusters) > 0 {
Fixed.

2021-12-05 20:17 UTC, shlomitk1 commented on manager/controllers/app/plotter_generator.go
> +		if len(item.Configuration.ConfigDecisions[app.Read].DeploymentRestrictions.Clusters) > 0 {
Fixed.

2021-12-05 20:19 UTC, shlomitk1 commented on manager/controllers/app/plotter_generator.go
> +		if len(item.Configuration.ConfigDecisions[app.Copy].DeploymentRestrictions.Clusters) > 0 {
Removed hard-coded logic. Storage allocation is still an issue, I'll open a discussion.

2021-12-06 09:30 UTC, closed without merging